name: pull-request
on:
  pull_request:
    branches: [ master, future ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Pixray code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install basicsr

      - name: Run unit tests
        run: python -m unittest